jobs:
- job: dockerBuildPushJob
  pool:
    vmImage: 'ubuntu-18.04'
  steps:
    - task: Docker@2
      displayName: Login to Docker Hub
      inputs:
        command: login
        containerRegistry: DockerHubConnection
    - task: Docker@2
      displayName: 'Build and Push'
      inputs:
        command: buildAndPush
        containerRegistry: DockerHubConnection
        repository: yamadakoji/teachhub
        tags: latest
        Dockerfile: Dockerfile
        buildContext: .
