# Generated by Django 3.1.3 on 2021-07-15 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, verbose_name='章')),
            ],
            options={
                'db_table': 'chapters',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128, verbose_name='学校')),
            ],
            options={
                'db_table': 'schools',
            },
        ),
        migrations.CreateModel(
            name='SchoolClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128, verbose_name='学校区分')),
            ],
            options={
                'db_table': 'school_classifications',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128, verbose_name='科目名')),
            ],
            options={
                'db_table': 'subjects',
            },
        ),
        migrations.CreateModel(
            name='Textbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128, verbose_name='教科書')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='textbooks', to='teachhub.subject', verbose_name='科目')),
            ],
            options={
                'db_table': 'textbooks',
            },
        ),
        migrations.CreateModel(
            name='SubjectArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128, verbose_name='教科名')),
                ('school_classification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subject_areas', to='teachhub.schoolclassification', verbose_name='学校区分')),
            ],
            options={
                'db_table': 'subject_areas',
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='teachhub.subjectarea', verbose_name='教科名'),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128, verbose_name='節')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='teachhub.chapter', verbose_name='章')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='teachhub.subject', verbose_name='科目')),
                ('textbook', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='teachhub.textbook', verbose_name='教科書')),
            ],
            options={
                'db_table': 'sections',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=128, verbose_name='資料名')),
                ('category', models.CharField(blank=True, default='', max_length=128, verbose_name='カテゴリー')),
                ('path', models.TextField(blank=True, default='', verbose_name='保存先')),
                ('content', models.TextField(blank=True, default='', verbose_name='資料説明')),
                ('updated_by', models.TextField(blank=True, default='', verbose_name='更新者')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('created_by', models.TextField(blank=True, default='', verbose_name='作成者')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('custom_user', models.CharField(blank=True, default='', max_length=128, verbose_name='ユーザー')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='teachhub.chapter', verbose_name='章')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='teachhub.section', verbose_name='節')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='teachhub.subject', verbose_name='科目')),
                ('textbook', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='teachhub.textbook', verbose_name='教科書')),
            ],
            options={
                'db_table': 'documents',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='subject',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='chapters', to='teachhub.subject', verbose_name='科目'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='textbook',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='chapters', to='teachhub.textbook', verbose_name='教科書'),
        ),
    ]
